[package]
name = "oxiclean"
version = "1.7.2"
edition = "2021"
description = "Fast cross-distribution Linux system cleaner"
authors = ["croaky-fx <217624563+croaky-fx@users.noreply.github.com>"]
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "=4.5.20"
colored = "2"
ureq = { version = "3", features = ["json"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
